### ISSUE TITLE
Homey not pairing with Hue bridge

### ISSUE THREAD

**Issue by dvanp** [athombv/nl.philips.hue#10]
On 0.8.35 (clean wipe) Homey is not pairing with my the bridge. Had issue on 0.8.32 as well and skipped 0.8.34. Pairing is working with other devices, so I'm quite sure it's not the bridge.

Log after trying to pair: 3E15B99F5F

**Comment by WeeJeWel** [comment]
Your log shows Homey can't resolve domain names. Maybe your router's DNS doesn't work?

**Comment by rikdingemans** [comment]
I am on 0.9.1 and it is not possible to pail the Hue Bridge V2. Both Hue and Homey are in the same network, same subnet. With the Hue app on my iPhone on Wifi the Bridge can be reached without problems. Already gave the Hue Bridge a reset to factory defaults, no results.

**Comment by rikdingemans** [comment]
Issue seems to be fixed in 0.92 and thanks to on-site support from @thayoung1

**Comment by bvdbos** [comment]
@dvanp is this fixed?

**Comment by WeeJeWel** [comment]
Resolved in the current git version (will be finalized soon)
