### ISSUE TITLE
Color of Trådfri RGB can't be controlled by Homey

### ISSUE THREAD

**Issue by rasssta** [athombv/nl.philips.hue#100]
The title says it all I guess :)

It's not possible to change color of Trådfri light bulbs that are connected to a Hue Bridge.

**Comment by rasssta** [comment]
I should add that it works fine from the Hue app, but not from Homey iOS beta-app nor the Homey web interface.

**Comment by rasssta** [comment]
Any news on when this will be fixed?

**Comment by jeroenbos22** [comment]
Possible fix: https://github.com/sqmk/huejay/issues/96

**Comment by WeeJeWel** [comment]
Unfortunately, non-Hue devices are not officially supported.
