### ISSUE TITLE
Lots of DNS requests 3000x more than the bridge it self

### ISSUE THREAD

**Issue by DanielTromp** [athombv/nl.philips.hue#103]
All day long and every minute the Hue App on the homey queries the dns 2 times for "www.meethue.com", this seems very unnecessary. The app on the phone only queries it once when in use as a regular app does. Maybe use cache in the app, it's now hitting the cache on my pi-hole for no real reason (I assume). Other applications query every hour or 8 hours, can you reduce this.
Mayby unrelated but my first HUE bridge that is connected with meethue.com has had allot of issues untill I disconnected it from meethue.com and now it seems fine.

**Comment by WeeJeWel** [comment]
This is a Homey core issue and will be solved in an upcoming update.
