### ISSUE TITLE
Add support for the new "Friend Of Hue Switch"

### ISSUE THREAD

**Issue by DarkCinema** [athombv/nl.philips.hue#109]
Please add support for the new "Friend Of Hue Switch".
More info:  https://www2.meethue.com/nl-nl/friends-of-hue/niko

Contect me If you need more info about the hardware.

Bridge Info:

			"name": "Friends of Hue Switch 1",
			"description": "Friends of Hue Switch 1 behavior",
			"type": "Link",
			"classid": 10050,
			"owner": "***",
			"recycle": false,
			...

			"name": "Friends of Hue Switch 1",
			"type": "ZGPSwitch",
			"modelid": "FOHSWITCH",
			"manufacturername": "PhilipsFoH",
			"productname": "Friends of Hue Switch",
			"uniqueid": "****",
			"capabilities": {
				"certified": true
				...

**Comment by WeeJeWel** [comment]
Unfortunately, non-Hue devices are not officially supported.
