### ISSUE TITLE
Removing all devices

### ISSUE THREAD

**Issue by Fire69** [athombv/nl.philips.hue#11]
I wanted to remove all my Hues from Homey to test if this solved my problems with the Android app (unreachable devices)
So I removed the app from Homey. It warned me that all devices and settings would be removed.  Perfect, that's what I wanted.

After removing the app, all my lights were still there... When I opened the card, I had an error about an invalid id.
So I had to remove all 25 lights manually myself...

Was this the correct procedure to fully remove everything related to Hue from Homey?

**Comment by WeeJeWel** [comment]
You probably needed to refresh the list of devices I suppose. Are you refering to Mobile or Zones & Devices?

**Comment by Fire69** [comment]
They were left in the Zones & Devices, because of that they were also visible in the mobile view and the android app.
What do you mean with 'refresh the list of devices'?
Anyway, can't test anymore, did a full reset already in the mean time ;-)

**Comment by WeeJeWel** [comment]
Alright. With refresh I meant a webpage refresh. 

I'll close this issue for now. If it happens again, please report it again in athombv/homey
