### ISSUE TITLE
hue crashes Homey 0.8.35

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.philips.hue#12]
https://github.com/athombv/homey/issues/649#issuecomment-222495020

**Comment by sossienl** [comment]
It could be that the HUE app is not the root cause. My Homey is still unresponsive now and then, but it does respond to commands, with a huge delay. So in my case it could be that the HUE app needs a lot of resources (read memory) because of the amount of devices.

**Comment by mruiter** [comment]
crashes every hour with a red ! and undefined error on .35 .34 and .32 gave a yellow ! in apps.
As also reported on slack and the forum many people have a crashing hue app.
aits not workable anymore

**Comment by mruiter** [comment]
Oh and gives us that 1.x release there is a screenshot of. Been waiting for weeks to have something thats stable again and isnt a community app

**Comment by WeeJeWel** [comment]
I'm 99.999% certain that Hue is not the reason of Homey crashes ;-)
