### ISSUE TITLE
Not able to add hue lights anymore 

### ISSUE THREAD

**Issue by Deentje** [athombv/nl.philips.hue#13]
Hi Athom,

I have Homey version 0.8.35 and hue app version 1.0.0 installed and since today I can not add any lights anymore.
When selecting a device and the hue i get the following screen 
![hue tab](https://cloud.githubusercontent.com/assets/19371484/15792881/81a3a61a-29e0-11e6-9329-1fd4f4e3cb0d.jpg)

When I press the button on the Hue bridge I get the following message immediately:
![hue tab 2](https://cloud.githubusercontent.com/assets/19371484/15792927/dcb4e9f6-29e0-11e6-962d-c8e82b778e38.jpg)

I already restarted homey twice.  Could it be caused by the last Hue app update to V1.0.0?
Any other suggestions what to try?

**Comment by Fire69** [comment]
Some problem here.
Because of another problem, I removed the Hue app, so all my lights were gone.
When I want to add my Hues again, I tap the button and only 2 lights are found instead of ~20

Hue app 1.0.0 and Homey 0.8.36

Tried removing/installing app again, rebooting Hue bridge, removed all users ('Homey' from old app version and 'Node.js API' from current version?) from Hue bridge.  Nothing works.

**Comment by philsniff** [comment]
Same here 

Hü app 1.0.0 and Homey 0.8.36

**Comment by Fire69** [comment]
Solved with 1.0.2 here

**Comment by Deentje** [comment]
I noticed my homey automatically updated to 0.8.36 while I did not select the install button. Though after the update to 0.8.36 my hue lights were not reachable anymore. I restarted homey again but did not work. So I removed the hue app and reinstalled it  (v1.0.2). After selecting a device and the hue app and clicking the button on the bridge all the bulbs show up again. After re-installing it works again.

**Comment by Deentje** [comment]
Maybee I was a bit too quick, after a reboot again my living white plugs became again unreachable. 
The hue app on my smartphone sees them and I can switch them on/off withouth a problem. So I guess the bugg is somewhere in the homey hue app

**Comment by Deentje** [comment]
The Update of the Hue app on homey to 1.0.5 fixed the issue for me.

**Comment by bvdbos** [comment]
@Deentje then you can close this issue?

**Comment by WeeJeWel** [comment]
Resolved in the current git version (will be finalized soon)
