### ISSUE TITLE
in version 1.0.2 adding  a new hue bulb requiers a new user on the bridge

### ISSUE THREAD

**Issue by nattlip** [athombv/nl.philips.hue#15]
that can't be the idea.

**Comment by Fire69** [comment]
Not a 1.0.2 problem.
I'll quote myself from the comments section of the Hue app (from 2 months ago):

>I still don't get why I have to push the button on the bridge again when I want to add a new light... There was an issue on github about this, but it was closed with a (imho) stupid reason... You want to keep it simple (cfr Emile's mom) but then you say it's for people with multiple bridges? How many users would that be?? My bridge is stashed away, I always have to go grab a chair and move stuff around for this! Plus you clutter your bridge with unnecessary users... Plus you complicate things because different lights then use different users to connect to the bridge. Sorry, totally don't get the logic behind this way of working... :-/

IMHO new lights you add to your bridge should appear automagically, like I see it in any normal Android app.

If you want support for multiple bridges, just add an extra screen to the device setup wizard where you ask if you want to add an extra bridge.

**Comment by bvdbos** [comment]
Is this fixed?

**Comment by WeeJeWel** [comment]
Resolved in the current git version (will be finalized soon)
