### ISSUE TITLE
LivingColors/LivingWhites turns on at minimum level

### ISSUE THREAD

**Issue by Fire69** [athombv/nl.philips.hue#19]
I'm using Homey to turn on some Hues and an Iris at sunset and turn them off with a flow when I go to bed.
It seems like the 'turn off' command doesn't just turn off the Iris, but also sets the level to 0 (or near 0).
As a result, when it's turned back on, it's at the minimum level.
This doesn't happen with the Hues (Color, Lux or White models).
I did some more testing, and it also happens with my LivingWhites bulbs.

**Comment by WeeJeWel** [comment]
Fixed
