### ISSUE TITLE
Lights turn back on after few seconds

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/nl.philips.hue#21]
Im on firmware 0.8.39, when I say 'turn all lights off' my hue lights turn off (together with all other lights). But after approx 2 sec the Hue lights turn back on (to the latest dimvalue).

Happens also when I manually turn them of in the app, when I do it in the Hue app itself they stay off.

**Comment by WeeJeWel** [comment]
Sounds like you have a flow running that turns them on. Can you confirm
that isn't the case?

**Comment by jeroenbos22** [comment]
Apparently I had a broken flow (it had a Smartwares sensor wich because of the update got deleted) wich activates a flow to dim the Hue. Can it be (maybe bug) that if a flow is broken it gets fired every x seconds?

**Comment by WeeJeWel** [comment]
Can you post a screenshot of the flow?

**Comment by jeroenbos22** [comment]
Hmmm, that didn't fix it. It's still going on after a few seconds, no flow that triggers it.

**Comment by bvdbos** [comment]
@jeroenbos22 Does this still happen?

**Comment by WeeJeWel** [comment]
Im closing this issue. If it persist, please let me know :)
