### ISSUE TITLE
Lights unreachable

### ISSUE THREAD

**Issue by ralfvd** [athombv/nl.philips.hue#24]
Since Homey version 0.10.0 ( also confirmed on 0.10.1 ) all Hue lights are reported unreachable even after a clean install. 

When adding the lights when the lights are actually turned on, they can be controlled until the next reboot of Homey. But once 'unreachable' they never go back in an on-line state.

"Crash" log: 0AA3717981

**Comment by Arjanvde** [comment]
Got the same issue.

@ralfvd  what worked in my case, was going to devices and trying to add a Philips light. When I pressed the button on the bridge (when Homey says so) all lights are popping up.

**Comment by ralfvd** [comment]
Does that trick survive a reboot in your case? In my case, it didn't

On 29 Sep 2016 at 21:24:22, Arjanvde (notifications@github.com) wrote:

Got the same issue.

@ralfvd <https://github.com/ralfvd> what worked in my case, was going to
devices and trying to add a Philips light. When I pressed the button on the
bridge (when Homey says so) all lights are popping up.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/nl.philips.hue/issues/24#issuecomment-250565939>,
or mute the thread

**Comment by ralfvd** [comment]
Some additional information; when running the app in --run mode, the only output I get is this:

-------------------------------------------------
nl.philips.hue running...
Found bridge! ID: NNN, IP: 192.168.nn.nn 

I don't see the "found bulb" logging, that based on my quick scan in the code, should be there.

**Comment by ralfvd** [comment]
When logging the 'bridge' variable in the refreshBridge code, this is the result:

{ ipaddress: '192.168.nn.nn', api: false, lights: {} }

Given that bridge.api is false, it doesn't try to get the light state.

**Comment by Arjanvde** [comment]
@ralfvd That trick doesn't survive a reboot, but it prevents me of re-adding all HUE lights again.

**Comment by elcovb** [comment]
Same problem here. All lights offline. Here adding the bridge again and pressing the button doesn't help.

**Comment by bvdbos** [comment]
@elcovb Are your lights still offline after 0.10.3 FW? @Arjanvde : The settings should now persist after a reboot after the changes in 0.10.3 FW?

**Comment by elcovb** [comment]
@bvdbos no all lights are working again :).

**Comment by Arjanvde** [comment]
@bvdbos this now working as expected.
