### ISSUE TITLE
Github version is different than appstore version

### ISSUE THREAD

**Issue by Arjanvde** [athombv/nl.philips.hue#25]
Please note that there is a difference in the version of the Philips HUE lights which is currently on github and is available on the app store. If the Github version is installed manually through the CLI the colorloop start and stop card are added and there is an option to set the colorloop time in seconds. 

Both are version V1.0.5

**Comment by WeeJeWel** [comment]
I'm going to fix some Hue issues soon, and will then push the new version to the appstore!

**Comment by bvdbos** [comment]
Don't forget the pending pull-requests.

**Comment by WeeJeWel** [comment]
App Store version updated!
