### ISSUE TITLE
Response 'Ik kon geen lampen vinden om uit te zetten' when there are lights in a room

### ISSUE THREAD

**Issue by ThaYoung1** [athombv/nl.philips.hue#26]
When I say 'Ok Homey, zet de lampen uit in de keuken' Homey replies with the Response mentioned in the title. 

I'm using firmware v0.10.1 and Dutch language.

**Comment by sossienl** [comment]
**Same here**

**Comment by WeeJeWel** [comment]
This is most definitely not a Hue-specific issue, so if it still occurs, I advice you to make an issue here: https://github.com/athombv/homey/issues
