### ISSUE TITLE
homey does not pair with old bridge version

### ISSUE THREAD

**Issue by blackice2k3** [athombv/nl.philips.hue#27]
Hi Homey Team,
I tried different ways to get a connection with the old Philips hue bridge.
Version: 0.10.3
Hue app: 1.0.5
I tried pressing button before start pairing. I tried it after. I tried while start pairing. Nothing works. 
Reinstalling the app or reseting homey nothing helped for now.
Also the debugging of the app with cli does not work. 
![hue](https://cloud.githubusercontent.com/assets/22826045/19369086/8c1e824c-91a3-11e6-85b1-1e3f0e7dc461.PNG)
After 10 minutes I stopped debugging because it never gets 4/4. 
Any other suggestions what to try?

**Comment by WeeJeWel** [comment]
Resolved in the current git version (will be finalized soon)
