### ISSUE TITLE
Not all Hue lights in group respond

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.philips.hue#28]
https://github.com/athombv/homey/issues/94

**Comment by sossienl** [comment]
Same here

**Comment by WeeJeWel** [comment]
I hope to have this fixed in the newest (git) version. But it's actually a 'bug' in the Hue bridge itself, that it can't handle too much traffic, yet it reports 'OK'.

Please report back if it still happens, then I need to finetune the command queueing.

**Comment by sossienl** [comment]
So how do I test this? I have 20+ hue lamps and experiencing a lot of random issues. Sometimes all lamps in a room respond, sometimes one is not. but again completely random.

When I control the lights via Hue app, no problems.

Can't we consume the groups and scenes? and activate those?

**Comment by sossienl** [comment]
So to overcome this until HUE is properly implemented, is to call the scene for a group directly using the API. This will require some work, but by using the HTTP Flow card app to trigger a HTTP Put JSON, you can set a specific scene for a group / room. This wil always work and overcomes the implementation issue.

**Comment by sossienl** [comment]
Ok wow. this will also not work in every case, because setting the lights via this option (you can also turn off all lights in a group), Homey doesn't detect that, and will still think they are on.

Can someone explain how often Homey 'syncs' with HUE to get a actual state?

**Comment by sossienl** [comment]
Seems to work perfectly with the 2.0+ update

**Comment by bvdbos** [comment]
I didn;t read any comments about this issue lately so closing...
