### ISSUE TITLE
Homey can not pair with two hue bridges and can not handle two bridges in the same network

### ISSUE THREAD

**Issue by spoelly** [athombv/nl.philips.hue#29]
Currently Homey can not pair with two Hue bridges.
Also if i just want two pair one of the bridges and leave the other one. This is not possible. 

When there are two ip-adresses used by Hue bridges, Homey can not handle any pairing.
https://www.meethue.com/api/nupnp

If you only got one bridge it works perfectly. 

The Philips Hue app is able to handle two or more bridges in the same network, homey is currently not able to do this.

**Comment by WeeJeWel** [comment]
Resolved in the current version (will be finalized soon)
