### ISSUE TITLE
Adding new lights should not require a new API key

### ISSUE THREAD

**Issue by AndreSomers** [athombv/nl.philips.hue#3]
If you do not add all lights in one go, either because the lights are in different rooms or because you just added a new light in your Hue setup, you will find that you have to press the bridge button again. This means that the app is requesting a new API key. It should not. Once an API key has been requested, this is the key that should be used for all lights.

**Comment by WeeJeWel** [comment]
This is intended behavior, because when you have multiple bridges, Homey can't discriminate between them (and showing bridge IP addresses is highly geeky)

**Comment by AndreSomers** [comment]
It is bad behaviour if you don't have multiple bridges. Please don't complicate the common case in order to support the uncommon one.

**Comment by freemann** [comment]
Ask user on beginning of pairing how many bridges he wants to add.

**Comment by AndreSomers** [comment]
Or just query all known bridges directly, and a separate item somewhere in that UI to add another bridge for if the user added one.
