### ISSUE TITLE
Add support for Hue switch logic

### ISSUE THREAD

**Issue by markaswift** [athombv/nl.philips.hue#31]
If possible, please add flow logic for the following switches so we can use them in flows.

i.e. If button 1 on Hue Tap is pressed, we can also use the event to trigger flows.

Please support both types of switch:

http://www2.meethue.com/en-us/productdetail/philips-hue-dimmer-switch
http://www2.meethue.com/en-us/productdetail/philips-hue-tap-switch

Thanks guys!

**Comment by WeeJeWel** [comment]
Done!
