### ISSUE TITLE
Lights need to be re-added with V2.0

### ISSUE THREAD

**Issue by Arjanvde** [athombv/nl.philips.hue#33]
After i've installed the github repo, i had to re-add all my HUE devices before I could use this version. Reinstalled the app store version and all lights worked again. 

Not going to continue with this version since a software update requires to add them all again probably.

**Comment by WeeJeWel** [comment]
This version did not change any settings do this shouldn't have been necessary. What made you think that the devices didn't work after install, e.g. an unavailable message?

**Comment by Arjanvde** [comment]
Yes, all lights became unavailable after installing this repo.

**Comment by Arjanvde** [comment]
Keeps giving this message:

[001788FFFE1CD137] _refreshDevices
[bulb][log] _syncDevice 00:00:17:88:01:00:cb:1c-0b
[bulb][log] _syncDevice 00:17:88:01:00:cb:1c:f4-0b
[bulb][log] _syncDevice 00:17:88:01:00:db:8a:b3-0b
[bulb][log] _syncDevice 00:17:88:01:00:de:03:d1-0b
[bulb][log] _syncDevice 00:21:2e:ff:ff:00:9f:b4-0a
[bulb][log] _syncDevice 00:17:88:01:00:cb:73:3e-0b
[bulb][log] _syncDevice 00:17:88:01:00:c4:b9:1e-0b

**Comment by WeeJeWel** [comment]
Then that's a bug, because the settings really didn't change :)

**Comment by Arjanvde** [comment]
Good luck solving it 😄 

In case I can help, just let me know.

**Comment by Arjanvde** [comment]
Fixed!
