### ISSUE TITLE
Lamp state not updated after triggering scene

### ISSUE THREAD

**Issue by sossienl** [athombv/nl.philips.hue#34]
When I trigger a scene in a flow, the state of the lamp is not changed.
The use-case; when lights are on and there is movement trigger  sceneB and activate a timer that will reset the lamps to sceneA once it's done.

but because of the check if a light in that group is actually on, will return false instead of true, keeping it from continuing the flow

**Comment by WeeJeWel** [comment]
This should happen within 10 seconds. Doesn't it?

Homey does not synchronize the lights directly after the scene, because it doesn't know which lights are in a scene.

**Comment by sossienl** [comment]
Yes working with 2.0 +
