### ISSUE TITLE
No voice confirmation when giving a voice command: ie. turn the lights off

### ISSUE THREAD

**Issue by Tweaqer** [athombv/nl.philips.hue#36]
Doesn't give a voice confirmation when you give a voice command: ie. "turn the lights off". It used to respond with: "turning lights off"

**Comment by bvdbos** [comment]
@Tweaqer does this still happen? And do your lights go out: both Hue and other lights?

**Comment by Tweaqer** [comment]
Nope. it's fixed. Thanks :)
