### ISSUE TITLE
Speech lable of Homey is not correct

### ISSUE THREAD

**Issue by Pieterman85** [athombv/nl.philips.hue#39]
Hi,

I think this is located in the Hue app.
When I say to Homey (in Dutch) "Zet de lampen op groen", the feedback Homey gives is Dutch except the color the lamps where set to. The color name is always pronounced in English.

ie: Homey: "Ik zet de lampen op [green]"

**Comment by Tweake** [comment]
I forgot to give an update on this issue, but it was fixed in Homey update 1.0.4. Thanks for reporting the issue!
