### ISSUE TITLE
Version 0.9.12 won't pair with Homey

### ISSUE THREAD

**Issue by moekdegroot** [athombv/nl.philips.hue#4]
After installing 0.9.12 and wanting to add some more lights homey didn't want to pair anymore.
I uninstalled/reinstalled/rebooted the app/homey and even reset the hue hub.
My iphone apps all pair as usual but homey is stuck at the "press the pairbutton-window"

**Comment by WeeJeWel** [comment]
What's your Homey version?

**Comment by moekdegroot** [comment]
Sorry, 0.8.24

**Comment by cnvisser** [comment]
I'm experiencing the same. 
My homey is 0.8.24 and it happened after i installed the Hue app 0.9.12.
The Hue hub is 1.11.1.0.

-Reset Homey didn't work
-Reset Hue hub didn't work
-Android Hue app on phone works as normal

**Comment by WeeJeWel** [comment]
Fixed in 0.9.13. Sorry!

**Comment by moekdegroot** [comment]
Thx @emile !
