### ISSUE TITLE
LivingWhites plugs not turning off

### ISSUE THREAD

**Issue by Fire69** [athombv/nl.philips.hue#40]
I have a couple of LW plugs on backup that I only use for festive lighting, so I hooked up my wife's Xmas lights (too soon, I know... :-/ )

But they're acting funny.
I have 3 of them in a flow to turn them off, but 1 consistently refused to turn off, 1 sometimes and 1 is always OK...
So I tested it manually with the device card.  When I turn it off in the card, the plug doesn't turn off and after a couple of seconds (the time for the polling I guess) the card shows it going back to on...
After a couple of tries it usually works to turn it off.
Here's a log: 9864274A45
If you need more info, just let me know. :-)

**Comment by Fire69** [comment]
Hm, you can ignore this for a bit, might have found the issue...
I'll let you know :-)

**Comment by Fire69** [comment]
I'm going to close this because the problem doesn't seem just related to the LW's.
I have 'normal' Hues that don't always react either.  I'll make a more general issue for it.

**Comment by bvdbos** [comment]
I've seen this mentioned on the forum so if you have a use-case please open up an issue. Did you run the app with logging on? Are the calls to the bridge made correctly?

**Comment by Fire69** [comment]
Did some logging, it's not only LW's, but it's hard to troubleshoot because it only happens 1 in 10 times...
I'll make a new issue for it.
