### ISSUE TITLE
Scenes wont show

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/nl.philips.hue#42]
My Scene list stays empty in Homey while I made quite a bunch of them. I made them after I installed the Hue app on Homey (months later). Dont now if it has anything to do with the problem but think I mention it :) 

I have this problem for a long time already, now on Homey firmware 1.0.5 at the moment.

![schermafbeelding 2016-12-20 om 19 40 39](https://cloud.githubusercontent.com/assets/19820589/21363320/54803e4c-c6ec-11e6-9860-c3aedea23985.png)

**Comment by jeroenbos22** [comment]
I have a 1st gen bridge BTW

**Comment by WeeJeWel** [comment]
Created issue at https://github.com/sqmk/huejay/issues/74

**Comment by CyberSponk** [comment]
Got the same since 1.3-RC11 > https://github.com/athombv/homey/issues/1617. On 1.2.2 selecting Scenes worked.

**Comment by WeeJeWel** [comment]
Verified working in v3.0.0
