### ISSUE TITLE
changing bridge-ip looses bridge and lights

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.philips.hue#43]
If the HUE-bridge is on a DHCP-network, the bridge might regularly get a new ip. If the device is lost including all lamps, flows etc. Perhaps some error-checking and updating should be done? If bridge not found then discover new adress and update settings?
https://forum.athom.com/discussion/1802/philips-hue-lights-unreachable#latest

**Comment by WeeJeWel** [comment]
Fixed by https://github.com/athombv/nl.philips.hue/commit/801d33e461acb15b1d8bdac68412dabb74387ae6
