### ISSUE TITLE
Device is still being synced when removed

### ISSUE THREAD

**Issue by denniedegroot** [athombv/nl.philips.hue#49]
After deleting a device the device is still being synced.

> [log] [DriverBulb] _onExportsDeleted { id: '00:01:02:03:04:05:06:07-0b', bridge_id: '001788fffe2514ed' }
[log] [DriverBulb] _uninitDevice { id: '00:01:02:03:04:05:06:07-0b', bridge_id: '001788fffe2514ed' }
[log] [Bridge][001788fffe2514ed] _refreshDevices
[log] [DriverBulb] _syncDevice 00:01:02:03:04:05:06:07-0b

**Comment by WeeJeWel** [comment]
Fixed!
