### ISSUE TITLE
Livingwhites / Lux / White properties

### ISSUE THREAD

**Issue by Fire69** [athombv/nl.philips.hue#5]
Hi,

Just noticed that for the Livingwhites plugs / lamps, Lux and White there are flow cards to set the color.
Obviously, these devices do not support color :-)

Thanks

**Comment by WeeJeWel** [comment]
What Homey version are you running?

**Comment by Fire69** [comment]
Homey: 0.8.32
Hue: 0.9.14

**Comment by WeeJeWel** [comment]
Should be fixed in v1.0.0. Please re-add your devices.

**Comment by Fire69** [comment]
Yep, it's correct now.
Thanks!

**Comment by bvdbos** [comment]
@Fire69 closeme :-)
