### ISSUE TITLE
Lights not responding sometimes

### ISSUE THREAD

**Issue by Fire69** [athombv/nl.philips.hue#53]
I made an issue for LW's but I'm having it with Hue Whites also sometimes.
https://github.com/athombv/nl.philips.hue/issues/40
As said there, it's hard to troubleshoot, there's no real logic in it.

I have 3 use cases.

Case 1: 3 LivingWhites plugs turned off with a BL bitflip:
```
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:00:2e:af:dd-0c false
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:00:2e:af:a0-0c false
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:00:2e:95:3f-0c false
```

Commands seem to be sent correctly but especially these don't turn off very often.

Case 2: 3 Hue Whites switched with a flow through a Fibaro z-wave Relay (not physically connected of course:-P )

Depending on whether it's before or after sunset, these are set to 100% or 50% (100% in this case):
```
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:10:30:cd:a5-0b true
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:10:30:cd:a5-0b true
[log] [DriverBulb] _onExportsCapabilitiesDimSet 00:17:88:01:10:46:98:4d-0b 1
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:10:46:98:4d-0b true
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:10:46:98:4d-0b true
[log] [DriverBulb] _onExportsCapabilitiesDimSet 00:17:88:01:10:46:90:cb-0b 1
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:10:46:90:cb-0b true
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:10:46:90:cb-0b true 
```

Commands seems weird, because this is the flow:
![image](https://cloud.githubusercontent.com/assets/1757287/21519204/9b3b3a26-cceb-11e6-8649-4ee344d3a302.png)

Don't know why there is 2x OnoffSet for each light, and the DimSet should come first...

Case 3: 1 Hue White being triggered by a Fibaro motion sensor:
```
[log] [DriverBulb] _onExportsCapabilitiesDimSet 00:17:88:01:00:de:47:6a-0b 1
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:00:de:47:6a-0b true
[log] [DriverBulb] _onExportsCapabilitiesOnoffSet 00:17:88:01:00:de:47:6a-0b true
```

Same thing here, OnoffSet being sent twice.

Annoying problem, especially for the light being triggered by the motion sensor.  I have to go away, wait until the sensors times out, then come back and hope the light turns on then.

**Comment by Tweaqer** [comment]
+1 for this issue, I also have the problem that my Hue lamps (mine are the 'White ambiance' ones that seem to have this problem)
