### ISSUE TITLE
Light auto on

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/nl.philips.hue#54]
Not an issue, more a suggestion. Would be nice that with cards like: Colorloop / Change color / set dim level etc first an on signal is send by default. Now I have to put in a bunch of double cards but only seems logical to me that if you ask for a color / colorloop the light is on. So if off automagically turn it on :)

**Comment by bvdbos** [comment]
Please no, if you have several lights on but not all, setting a dim shouldn't turn on all lights...

**Comment by jeroenbos22** [comment]
Then don't dim the lights that you want to stay off. Its only logical (and consistent with the way other lights work within homey (eg Kaku)) that they turn on when setting a dim level / colour etc. They also switch on if you change dimming level (wich in my opinion is correct behaviour).
If the light is not on it cant go do the setting you desired Homey to perform.
