### ISSUE TITLE
Reset light to default (power on) state

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/nl.philips.hue#55]
Would be nice if a reset light cards was added where it would go to the default state.

Got a number of lights that are manually turned on and then Homey sees motion. On motion I want it to react the same as power on. Now I have to gamble what color and brightness it is. This makes the lights change a little bit. Plus it is then in one card, now costs me 3 per light to do the same (on, color, brightness).

PS. You can find the default color / brightness to ask for these settings using the api directly after powering it on

**Comment by WeeJeWel** [comment]
Easiest to make a scene in the Hue app and trigger that using the app.
