### ISSUE TITLE
Lights on/off/dim commands not received when app is polling bridge

### ISSUE THREAD

**Issue by ralfvd** [athombv/nl.philips.hue#58]
When the app is polling the bridge and around the same time a on/off/dim command is sent, this command is not sent correctly by Homey or processed correctly by the bridge, resulting in no light on/off

Tested scenario:

- Changed lib/Bridge.js pollInterval to a large number (e.g. 3 hours ) : lights on/off works
- changed pollInterval to 1 second ; most commands don't have an effect on light status

When the pollInterval is set to one second, I can still manage the lights via the HUE app on my phone, only commands via Homey don't work anymore.

**Comment by WeeJeWel** [comment]
That's a great find. I'm going to investigate further, thanks!
