### ISSUE TITLE
Flow parameter tags are not updated.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/nl.philips.hue#59]
I try to store the tag-data of a Hue Lightstrip Plus in a few variables, so I can restore them to this 'previous' state after the light had a color-party.

Storing and restoring the tags seems to work fine, except that the tags don't seem to contain the current values for the lightstrip.
Whenever I change the color on my Hue-app, the data is not updated in the tags... not in 7.5 seconds, not in 10 seconds, not in a minute. 

So... Hue-tags do not seem to work at the moment (v2.2.2) 

EDIT: Strange. It seems to be only that one lightstrip that has the problem... but it is the last device in the Tag-list (top menu desktop), maybe that's something.

EDIT2: Additional info in next post.

**Comment by OpenMindNL** [comment]
Additional research:

I think the problem might be the "Lamp-mode" parameter-tag for combined white/color hue lights, like Go, Richer Color Bulb and Lightstrip Plus..

I can store this tag in a string variable, but there's no way to restore the mode to the lamp.

It seems that when I store the other parameters in color-mode and restore them to the lamp, the lamp will switch to temperature-mode and from that moment on the Tags for that lamp will not be updated anymore.

**Comment by Rocodamelshe** [comment]
Cannot re-produce with the "normal" lightstrips

**Comment by OpenMindNL** [comment]
That's right Rocodamelshe. It's only a problem with the newer Hue lights that contain extra LEDs for richer color reproduction.
The older Hue lights don't have a mode-setting.

**Comment by OpenMindNL** [comment]
This bug is much easier to reproduce than I thought. 
I will post a new issue soon. This one is closed.
