### ISSUE TITLE
Living color always gets marked unavailable

### ISSUE THREAD

**Issue by nlrb** [athombv/nl.philips.hue#6]
My living color lamp, connected to the hub, always gets marked as unavailable ('Unreachable') in Homey after some time. However, when executing a command like 'turn on all hue lights', the living color also turns on. So it is reachable.
![image](https://cloud.githubusercontent.com/assets/11725674/14766600/5140ab10-0a11-11e6-96e9-e12166fd190e.png)
My guess is that the Philips API has a 'reachable' flag, but that this doesn't hold for living color lamps.

**Comment by WeeJeWel** [comment]
Try again with v1.0.0

**Comment by nlrb** [comment]
Issue is still there with 1.0.0. It stayed unreachable, so I deleted it and added it again. After 1-2 seconds it became marked as unreachable again.

**Comment by WeeJeWel** [comment]
Fixed in 1.0.4
