### ISSUE TITLE
When Wi-Fi network settings Homey can't connect to Hue Bridge anymore

### ISSUE THREAD

**Issue by Rob-Houweling** [athombv/nl.philips.hue#62]
Current behavior:
When I change things on my Wi-Fi network, for instance the SSID, Homey can't connect to the Hue Bridge anymore. There's no way to reconnect Homey but to uninstall and reinstall the app. Consequence is that you have to add the lights to the created flows again which is no fun at all.

Expected behavior:
I would expect Homey to be able to reconnect when attached to Wi-Fi. Somehow it appears that the Bridge is connected in Homey to the Wi-Fi network which seems illogical. All Hue apps connect fine when changing the Wi-Fi network. (I have 2 Wi-Fi networks and it doesn't matter which one I'm on, all apps just connect to the bridge after on time initialization on one of the networks).

When not being able to connect to Hue Bridge, provide a settings page to reconnect to Bridge by pressing the button on the bridge instead of having to reinstall the app.

**Comment by WeeJeWel** [comment]
I will investigate - the Hue bridge should automatically reconnect.

As a workaround, you can reboot Homey, or quickly disable & enable the app to restart it.

**Comment by Rob-Houweling** [comment]
Thanks for the quick reply. Both workaround are not working. So more like notworkingarounds ;)
If you want access or need logs or anything, let me know.

**Comment by WeeJeWel** [comment]
Should be fixed in v3.0.0
