### ISSUE TITLE
Hue bulb state not updated by Homey

### ISSUE THREAD

**Issue by Spaapen** [athombv/nl.philips.hue#63]
When switching the Hue bulbs on or off using a Hue dimmer or the official Hue app the state is not changed in Homey. So when i switch on the lights, Homey still shows them as off and vice versa. As far as i can remember it did work in versions previous to 2.2.2

**Comment by glijie** [comment]
here the status of all hue lights(bulbs and g10 fit) are randomly (some are) not updated when the lights are switched on when using a flow.
Before update Hue 2.2.2 i had never any issues with hue lights.

the hue lights can be switched off but all the flows where lights are used in the AND column (for confirmation if on or off) are now not working any more.

Hope for a quick solution,
 if no solution please provide the link with the previous version of the hue APP

**Comment by WeeJeWel** [comment]
Fixed
