### ISSUE TITLE
Philips hue - Verander helderheid over tijd

### ISSUE THREAD

**Issue by robiebab** [athombv/nl.philips.hue#66]
The card change light intensity over time is not working for philips hue in the flow. If you set the card to a certain level, it will not fade to that level, instead it is going off.

example: i set the card light intensity to 60% with 20 sec time. 

**Result**
the philips hue light is going off

**Expected Result**
the philips hue light is going to 60% light intensity whitin 20 sec time

**Comment by WeeJeWel** [comment]
Fixed in v3.0.0 (feature/sdk2)
