### ISSUE TITLE
Irregular Turn On

### ISSUE THREAD

**Issue by CyberSponk** [athombv/nl.philips.hue#67]
On irregular times a bulb is turn on and set 100%. How can this be fixed?

**Comment by WeeJeWel** [comment]
There's probably a Flow or some other external input causing this :)

**Comment by CyberSponk** [comment]
Tested/Watched here more than once e.g. today while all Flows are disabled: 
Leaving Home > All Lights off. After round about one Hour one Bulb is is turned on. 

I'm not alone with this. See here:
https://apps.athom.com/app/nl.philips.hue
the second input: Does this also fix problems with Homey spontaneous switching on lights?

**Comment by WeeJeWel** [comment]
Maybe the Hue bridge has timers set, and/or someone is using speech to turn on lights?

This app really doesn't do anything by itself, so the chance is very little if that's the reason.

**Comment by CyberSponk** [comment]
Will check HueBridge and Speech of other Devices at Home. Will come back with results.

**Comment by CyberSponk** [comment]
Tested it out and got a result:
Got 10 rooms, 10 Flows and 35 Lightify-Bulbs on HueBridge 
Lightify-App not working > Have had here Contact with @AnnemarieHuijink 

The Flow of each room turns all lights off in the room using the Hue-Feature "Turn off lights in room" with the room. If all the Flows runs the same time all bulbs are turned off and sometimes later one bulb is turned on again.

If the lights turned off with "Turn off lights in room" with "All Lights" no bulb will be turned on sometimes later.

I did not find out if this a problem of Homey or HueBridge.

**Comment by robiebab** [comment]
check if this occurs for example at 22:00 or 23:00? if so then you got youre answer (toonfrequent)

**Comment by CyberSponk** [comment]
@robiebab toonfrequent? you mean too much signals from hue?

**Comment by robiebab** [comment]
http://www.toonfrequent.nl/

**Comment by CyberSponk** [comment]
understand. but: now while i'm sitting here > one bulb turned on. did nothing. only sitting here.

this week, nobody was at home, one of the camera's at home told me that a unknown person was detected. looked the picture: it was not a person, it was a switched on bulb.

it's crazy ...

**Comment by robiebab** [comment]
can you post your flows?

**Comment by CyberSponk** [comment]
all (more than 100) or only the flows where the magic-bulb is included? checked all flows more than once so that i'm sure that the bulb is not in other flows. @robiebab have you seen my information on slack about ptp homey and hue-bridge > hi. tested it out some days (hope you know > hue and turn on lights). ptp homey > bulb will turned on. homey running and ptp hue-bridge > no light will turned on.
