### ISSUE TITLE
Homey doesn't connect with bridge

### ISSUE THREAD

**Issue by dreamflightexpress** [athombv/nl.philips.hue#69]
Hello,

I'm a new Homey user (I've been using it for more or less 1 week). I moved from Fibaro HCL to Homey to be able to integrate my Hue Lamps and Sonos Speakers in flows. Up to yesterday Homey was controlling:

- 2 Fibaro doorsensors
- 2 Aeotec windowsensors
- 1 Aeotec siren
- 1 Fibaro keyfob
- 3 Fibaro smoke detectors
- 2 Sonos Play 1 speakers
- 6 Hue lamps

Homey is running on 1.1.19. The Hue App v2.2.4

This morning I couldn't control my Hue Lamps with Homey. I tried a reboot of Homey and a reboot of the Hue bridge (version 1) without succes. I deleted and reinstalled the Hue App. After that I can no longer add my lamps to Homey. Homey recognises the bridge (with fixed IP address) but keeps asking "push the bridge button". No response whether I push the button before, immediately or with a short delay. Tried to disable/enable the Hue App several times but no succes in adding my lamps. I can control my lamps on my tablet with the Philips Hue App and can add the lamps on my Amazon Dot.

**Comment by WeeJeWel** [comment]
Is this still an issue?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
