### ISSUE TITLE
Blink lights

### ISSUE THREAD

**Issue by thuijbers** [athombv/nl.philips.hue#7]
I'd like to have the opportunity to blink the lights when something happens (or start a color loop). It's pretty easy when using the Hue Api, just use shortAlert() or alertLong() etc.

Any plans to add this in the near future?

**Comment by WeeJeWel** [comment]
That's a cool suggestion. Will add it when I have some spare time!

**Comment by caseda** [comment]
And while at it, why not be able to change the Transition Time?
Great for "Wake Up Light" like futures, or dimming more slowly to the "Movie Light Scene"
