### ISSUE TITLE
Add Hue grouped lights as a single device

### ISSUE THREAD

**Issue by Spaapen** [athombv/nl.philips.hue#72]
What is your Homey version (Settings → System)?

1.2.2

What did you try to achieve?

The option to add HUE grouped lights as devices.
Now we have to switch on all individual bulbs or use flows and/or bitflip devices which give some issues detecting the current state.

What did you expect as result?

There are no HUE grouped lights available, only individual bulbs

Any other remarks

See https://github.com/athombv/homey/issues/1324#issuecomment-298286212

**Comment by jeroenbos22** [comment]
Would also like this very much!

**Comment by CyberSponk** [comment]
Hue-Bridge: Create Scenes. Homey: In Flow start the Scene you made on Hue-Bridge.

**Comment by kukel** [comment]
I tried https://apps.athom.com/app/com.swttt.devicegroups and it works for me!

**Comment by WeeJeWel** [comment]
wontfix - If we'd to add such a feature it'd happen in Homey itself. For now the solution of @kukel works good enough.
