### ISSUE TITLE
Reachability lost on all devices on second bridge

### ISSUE THREAD

**Issue by DarkCinema** [athombv/nl.philips.hue#73]
Hi I have two HUE bridge (One V2 and one V1).  I seem to loose reachability status on all devices on one of the bridge.

Today I noticed that all devices on the V2 bridge were unreachable but the devices on the second bridge were ok. I restarted the HUE app and the situation was that all the devices on the V2 bridge were ok but now all devices on the V1 bridge are unreachable. If I delete a device on that bridge and add it again it works again for some time.

How can I help with troubleshooting this issue?

**Comment by WeeJeWel** [comment]
I had the same issue last week.

You can fix this by adding a device, selecting the bridge, press the pair button and close the window.

I will investigate how this could've happened.

**Comment by DarkCinema** [comment]
Ok thanks, I wil try your workarround in the meantime. If I can help with testing please let me know.
Nice APP btw.

**Comment by ruudcornelisse** [comment]
With me in recent days the lamps are also unavailable. But a restart of the hue app does not make sense, I really need to remove a lamp and add again

**Comment by WeeJeWel** [comment]
Should definitely be fixed in v3.0.0
