### ISSUE TITLE
No hue bulls, while Osram Plugs in hue bridge

### ISSUE THREAD

**Issue by andreasbeck** [athombv/nl.philips.hue#74]
While there are hue plugs in my hue bridge I can't import my hue bulbs to homey.
I can start the process, but there is only a loading icon for hours without result. When I delete the Osram Plugs, my bulbs are loaded immediately

**Comment by WeeJeWel** [comment]
Is this still happening on 2.2.6?

**Comment by andreasbeck** [comment]
Don't know if the problem is still existing. Since V1.5 I am using the Osram ZigBee app, so there is no need anymore for using the plugs within hue. Thanks for asking.

**Comment by CyberSponk** [comment]
@andreasbeck Could you change Color with a Flow?
