### ISSUE TITLE
Using the set colour card causes light to increase to 100% brightness.

### ISSUE THREAD

**Issue by Swiftnesses** [athombv/nl.philips.hue#75]
Fresh install.

**Comment by WeeJeWel** [comment]
That should depend on the color. For example #FF0000 means dim=1, hue=0, sat=1

**Comment by Swiftnesses** [comment]
Makes sense, but it isn't really ideal for obvious reasons.

Given I can set a colour in the Hue app without it effecting the brightness, can we achieve the same with Homey?

**Comment by WeeJeWel** [comment]
Maybe we'll solve this in the new app. Until then, use the 'set hue' and 'set saturation' cards.

**Comment by WeeJeWel** [comment]
Closing due to not being a Philips Hue specific issue.
