### ISSUE TITLE
After upgrade 1.5.0 RC2 no Hue bridge found

### ISSUE THREAD

**Issue by pdreissen** [athombv/nl.philips.hue#76]
After i upgraded to 1.5.0 RC2 the Hue Bridge is not found anymore. None of the Hue lights are reachable, how to fix ?

**Comment by WeeJeWel** [comment]
@pdreissen can you send me a message on Slack (@weejewel)? I'd like to fix this issue but cannot reproduce, so I need some logs.

**Comment by WeeJeWel** [comment]
Fixed!
