### ISSUE TITLE
Hue Lights don't turn off anymore

### ISSUE THREAD

**Issue by Tweaqer** [athombv/nl.philips.hue#78]
I'm on 1.5 rc2  with Hue v2.2.6 - 04.08.17.
I have two flows: 1) on motion turn light on 2) when motion alarm stops turn lights off.
A week ago they stopped being reliable turning off automaticly. I have Hue color and white ambiance bulbs.
Anyone else have this problem?
Cheers

**Comment by WeeJeWel** [comment]
Can you verify that this happens due to Hue and not due to the motion sensor?

**Comment by Tweaqer** [comment]
Now I can (data from this morning):
Lights:
![image](https://user-images.githubusercontent.com/20989897/29261592-98ed0efe-80d0-11e7-9d42-f03d15730fc8.png)

Motion (fibaro ms):
![image](https://user-images.githubusercontent.com/20989897/29261590-917d41f2-80d0-11e7-83d0-3644d05bc9ba.png)

**Comment by Tweaqer** [comment]
Havent had this issue for a while, might be fixed somewhere along the line of the updates
