### ISSUE TITLE
Missing key functions that limit app useability

### ISSUE THREAD

**Issue by jhaverkort** [athombv/nl.philips.hue#8]
First off all thank you for building this app!
Unfortunately I am missing support for key functionalities which makes the app not very usefull to work with right now.
- Philips Hue wireless dimmer support missing(http://download.p4c.philips.com/files/8/8718696506967/8718696506967_pss_nldnl.pdf)
- Missing support for hue groups & scenes in use in both flows and cards. Please add this like other Hue apps do. So as to have the ablity to turn on/off scenes or groups as defined.   Now I need to turn on 36 lights manually in the app!
- Remote Hue Tap Switch support missing
  (http://www.philips.nl/c-p/8718696498026/hue-tap-schakelaar)

**Comment by sossienl** [comment]
I agree with the point around the missing support for Groups and Scenes. This will probably also tackle the high traffic issues.

**Comment by WeeJeWel** [comment]
Tap + Switch support is added. Groups & Scenes is also added.
