### ISSUE TITLE
Hue dimming too low / hue doesnt turn on

### ISSUE THREAD

**Issue by Tweaqer** [athombv/nl.philips.hue#80]
I have an issue with the hue bulb in the hallway. Its inconsistant and sometimes it happens with my other bulbs as well but I choose the hallway to dive into this issue.

**The situaion**: I use a Fibaro Motion Sensor to turn the light on and off with these flows:
ON (fyi: dim level is set to 80%)
![licht aan-hal-flow](https://user-images.githubusercontent.com/20989897/29920410-b0b0af0c-8e4d-11e7-8a9e-0e070be7e62e.JPG)
OFF
![licht uit-hal-flow](https://user-images.githubusercontent.com/20989897/29920411-b0b48992-8e4d-11e7-8976-5ec2cbf104e3.JPG)

**The problem**: sometimes the light doesnt turn on and a lot of the time the dimming level is way too low.
Here's the insights (last couple of days) for this bulb:
![chart 2](https://user-images.githubusercontent.com/20989897/29920369-8445e40a-8e4d-11e7-8f11-965d7bb64f0e.jpeg)

blue: motion sensor/motion
purple: hue/on
green: hue/dim level

Please fix

**Comment by Veldkornet** [comment]
I’m having the same / similar problem. 

I have two Hue Iris lamps connected to a Bridge v2, which is then controlled by Homey. 
Basically I have a flow that turns them on when the tv turns on, and off when the tv turns off. 

Now my problem: Sometimes, one of the lamps turn on at a lower brightness, for example 10%, while the other is still on 100%. Then I set it back to 100% and it will be fine again for a few times. It really varies, it’s the on or the other, at random brightness levels.

**Comment by Tweaqer** [comment]
Yesterday the problem also occured in the attic. When the attic opens a fibaro doorsensor triggers the lamps to turn on:
![image](https://user-images.githubusercontent.com/20989897/30476448-5b041c6a-9a0a-11e7-9d14-165385d08021.png)

The hue lightstrip worked perfectly, but the bulb did not and only turned on with dimmed levels:
![image](https://user-images.githubusercontent.com/20989897/30476110-4ed20b42-9a09-11e7-9fbf-5a01d7f66fa9.png)

I've changed the flow instead of 'turn on' to 'set lamp to 100%'

**Comment by WeeJeWel** [comment]
Please try again with version `3.0.0` (can be found in the `feature/sdk2` branch)

**Comment by Tweaqer** [comment]
I installed it just now, I will try to give feedback later today/tomorrow and see how things fare :)

**Comment by Tweaqer** [comment]
Just tested it and issue still persists:
Flow
![image](https://user-images.githubusercontent.com/20989897/30903511-4e543a72-a36f-11e7-9058-4bf060d145c2.png)

Result checks out in insights:
![image](https://user-images.githubusercontent.com/20989897/30903849-74e2fe48-a370-11e7-9208-74bda82d9fd4.png)

However in real life the result (10:25 hr) was still more like 1-5% light. However when I went back to take a picture of the 1% result it worked and gave me 80% again.. (10:35 hr)

**Comment by WeeJeWel** [comment]
Seems like you might have set a transition time, because it's dimming over time? Otherwise looks like a faulty unit to me...

**Comment by Tweaqer** [comment]
hasnt occured in a while, i consider it fixed for now :) 👍

**Comment by Tweaqer** [comment]
I didn't have any mentionable issues with this up untill 1.5.3 but I think this changed in 1.5.6. Now in 1.5.8 this is a real issue again. Lights often do not turn on or turn on in the lowest dimmable brightness. Really annoying. Please fix.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2642
