### ISSUE TITLE
Timed brightness control does not set 0%

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/nl.philips.hue#83]
I'm using the flow card "Zet helderheid" + "0%" + "30 min" to gradualy dim lights until they are off.

In v3.0.x this doesn't seem to work anymore. The lights don't dim fully to 0%/off anymore.

**Comment by caseda** [comment]
This is not just with timed, this is with all flow cards that set the brightness to 0% (or trying lower)
So that includes the new relative dim card

**Comment by Keverjeroen** [comment]
I've got the same problem as OpenMindNL: https://forum.athom.com/discussion/comment/59641/#Comment_59641

**Comment by DeefK** [comment]
+1

**Comment by tlangelaar** [comment]
+1, now using an off card after x time as work around.

**Comment by caseda** [comment]
confirmed fixed in the beta app 3.0.2
