### ISSUE TITLE
Old dimming over time card puts lamps on 100%

### ISSUE THREAD

**Issue by caseda** [athombv/nl.philips.hue#85]
Hue App Version: 3.0.1
Homey Version: 1.5.3

**What did you try to achieve?:**
Use old flows with the (to-be) deprecated dimming over time card including changing color

**What was the result**
The lamp does change color (instantly), but the brightness (also instantly) goes to 100% and stays there.
If there is _no_ added color change then it just dims to the appropriate dim level.

It is _fixed_ when using new dim with time card, so it is only in the (to-be) deprecated card

**Comment by Povlov** [comment]
It is not "fixed" for me. As a wake-up routine Homey makes my hue lights simulate a daylight/sunrise.
For my purpose I do not think the alternative as described will work. Is there a possibility to maintain the gradual (un-)dimming of a light?

re: De Flow actie "Verander helderheid over tijd" zal in de toekomst worden verwijderd. Gebruik a.u.b. de Flow actie "Zet helderheid" met een "tijdsduur" waarde.

**Comment by caseda** [comment]
Are you using the __normal dim__ card with a "tijdsduur", it is displayed below the __delay__ timer option, it is not its b are anymore.

**Comment by Povlov** [comment]
Completely overlooked the symbol!! Tx.

**Comment by Povlov** [comment]
BTW..., this option would be very useful in the "Verander naar temperatuur" kaart. It could be used as a simple and effective daylight simulation.Where do I drop such an idea?

**Comment by caseda** [comment]
If you trigger the temperature and dim card with time at the same time, it will also fade with the temperature over time

**Comment by Povlov** [comment]
Ok. Thanks again. ;-)

**Comment by caseda** [comment]
But if you want the over time option on temperature (and color) too, then you would have to create another issue here with that feature request

**Comment by Povlov** [comment]
Works well like you described; parallel with a dim card with no actual change in dim value.
But of course, option on temp. and color cards would be more intuitive.
I will make a request,
