### ISSUE TITLE
Scenes and Rooms not shown

### ISSUE THREAD

**Issue by CyberSponk** [athombv/nl.philips.hue#86]
**What is your Homey version (Settings → System)?**
1.5.3

**What did you try to achieve?**
Hue-Card in a Flow in Then-Column. No Scenes or Rooms could be selected. Nothing Displayed for selecting.

**What was the result?**
Nothing. Nix. The result is that nothing could be selected.

**What did you expect as result?**
Selecting Scenes and Rooms in the Hue-Card.

**Any other remarks**
Issue is back and solved as written here: https://github.com/athombv/nl.philips.hue/issues/42

**Please attach a Homey System log (Settings -> System -> Send Log)**
If needed let me know.

**Comment by caseda** [comment]
Hmm must be something specific as mine show up just fine.

Do you have any v1 scenes/rooms maybe?

**Comment by CyberSponk** [comment]
How can i check/see the Versions?

**Comment by caseda** [comment]
You can see it in the windows (10?) app winHue, but there are probably more apps on android/ios that can do the same

**Comment by CyberSponk** [comment]
Looked on the Hue-Brideg and there are Rooms and Scenes V1. Made a reset of the Hue-Bridge and tested it with one Room and Bulb > Works fine. Thanks for help.

**Comment by caseda** [comment]
you might still want this issue keep open, v1 should work in homey as well imho, but at least narrowed the issue 😄
