### ISSUE TITLE
Living White Plugs settings can not be andjusted anymore after update to 0.8.35

### ISSUE THREAD

**Issue by Deentje** [athombv/nl.philips.hue#9]
After the update from 0.8.32 to 0.8.34 the living white plug settings under the device tab can not be opened anymore.

![living white plug not responding](https://cloud.githubusercontent.com/assets/19371484/15273313/aa614662-1a94-11e6-8551-f92c41796f1b.jpg)

Any idea what causes this, any idea how it can be fixed?

Regards

Deentje

**Comment by WeeJeWel** [comment]
Have you tried re-adding them?

**Comment by Deentje** [comment]
Yes, after re-adding still the same issue. When pressing the setting knob the small window opens and the searching circle keeps/stays spinning (like above picture)

**Comment by Deentje** [comment]
After update to 0.8.35 the issue changed a bit. When the settings tab is now opened i get the following:
![living white plug 2](https://cloud.githubusercontent.com/assets/19371484/15448965/8fb1405c-1f70-11e6-8123-bb39481d1362.jpg)

It is possible to switch on/off the light through a flow.

Regards

Deentje

**Comment by moekdegroot** [comment]
Had a similar error with some of my hue color bulbs.
After updating to 0.8.35 some gave the error "light_mode:invalid_type".
Removing them from the socket and screwing them back in solved it.
Hope it helps.

**Comment by Deentje** [comment]
In this case its the living white plug, I checked if it was solved when I removed it from the socket and reconnected it again, but issue is still there. It only shows this onoff:invalid_type when i select the settings of the device under the device tab. When I put the device in a flow you are able to change the brightness etc etc..

**Comment by moekdegroot** [comment]
Yes same here. After some time the lights showed the error again. It's related to another reported issue but can't remember which one.
