### ISSUE TITLE
Dimming duration 0 not possible, 0 = instant.

### ISSUE THREAD

**Issue by caseda** [athombv/nl.philips.hue#90]
App Version: 3.0.3

As the default transition time in hue is 200 milliseconds (0.2 seconds), which is a bit too slow for what i want to use it for.
i wanted to use 0 (instant) as a value as well in a certain situation (animation purposes).
and yes, it is definitely possible.
i can use 0.1 for now (the lowest possible, with a workaround, the lowest possible non 0 in hue is not working in the app apparently: 0.01) but 0 would be better.

not sure if it is even possible in the current homey implementation, as 0 usually means, not used, so maybe is not send as `opts` anymore.
if not possible yet, maybe it can then also be made possible to use a decimal in the duration selector.

**Comment by WeeJeWel** [comment]
We have defined `0` in Homey as `no duration`. Changing that would break some things so I'd rather not do that.

Sorry :)
