### ISSUE TITLE
White ambient candle, error on blink, but does activate

### ISSUE THREAD

**Issue by caseda** [athombv/nl.philips.hue#91]
app version: 3.0.3

The new white ambient candle light. (i guess the color version will do the same)

when activating the blink (short) and blink (long) it will give an error in the card: `Philips Hue: 6, parameter, effect, not available.`
but it does active the blinking animation.

**Comment by WeeJeWel** [comment]
Could you report this in https://github.com/sqmk/huejay ?

**Comment by caseda** [comment]
consider it done.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2641
