### ISSUE TITLE
Random color reverts back to light_temperature

### ISSUE THREAD

**Issue by caseda** [athombv/nl.philips.hue#92]
Hue app: 3.0.3

When setting the brightness ((non) default duration) _and_ a random color when `light_mode: temperature`, it will go to the random color, but very shortly (within 1 second) revert back to the previous light_temperature setting, even though the (new) brightness is applied properly, the brightness level doesn't have to change for it to revert.

If it already is in `light_mode: color`, then it works properly

**Comment by WeeJeWel** [comment]
What happens if you delay the 'random color' card for 1s?

**Comment by caseda** [comment]
I'll try when I get home, though that would break my slow transition to another random color flow, so not a permanent solution.
Probably is a race where the random color card always loses.

**Comment by caseda** [comment]
the random color card does work when adding a tiny delay to the card, but loose any transition.

just tested to set a normal color and brightness together, but that only sets the color, and not the brightness (brightness keeps spinning)
Thought that worked before, but apparently didn't look close enough.

light temperature does work properly/as expected, with and without brightness

**Comment by caseda** [comment]
Just something that might be the case, which I noticed when browsing through the code for the E14 bulb issue (but only thought of right now) 
Currently you have a 100ms wait time for capabilities, I have not seen this for flow cards, making it that all commands are send separately to huejay(?) 

Wouldn't that fix this issue by adding such a wait time?
And probably also the on with low dim issue (#80)

**Comment by caseda** [comment]
Noticed the new (default?) random color card since RC8, this one works, though the saturation isn't high enough (first trigger stays way above 80% which is too white), it might also be a core problem though?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2640
