### ISSUE TITLE
Memoryusage

### ISSUE THREAD

**Issue by daneedk** [athombv/nl.philips.hue#93]
While this issue https://github.com/athombv/nl.philips.hue/issues/79 is fixed, I still see a lot of memory usage by the hue app, especially compared to other apps that seem to use lesser memory after recent app/firmware updates.

The system uptime is 937984

![image](https://user-images.githubusercontent.com/16610696/33362627-9aa76274-d4dd-11e7-9309-371104655f85.png)

![image](https://user-images.githubusercontent.com/16610696/33362645-b71077ac-d4dd-11e7-94cb-fdb3109648d7.png)

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2639
