### ISSUE TITLE
After blink, the light stays on

### ISSUE THREAD

**Issue by Keverjeroen** [athombv/nl.philips.hue#95]
After a flow runs with an action to blink a Hue light, the light stays on. I use the latest version of the hub, with the latest firmware (1804201116). I’m not sure when this problem first occurred, but previously the bulb would turn off after a blink.

Firmwares: 
Homey: 1.5.11
Hue app: v3.0.4
Hue bridge: 1804201116

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2637
