### ISSUE TITLE
After migrating hub, app crashs on generic flow card 'All lights in one room off'

### ISSUE THREAD

**Issue by irritanterik** [athombv/nl.philips.hue#96]
Removed all old lamps and devices, migrated to new hub, added 'new' lamps; fixed flows.
Now the philips hue app crashes when the generic 'shut down specific devices' is used:

![image](https://user-images.githubusercontent.com/15232724/41807265-bccfb3b0-76cc-11e8-8c25-8787185766c1.png)

The unique log ID is: `bd72c32f-6e4d-43a1-9fe3-1e852b564041`

**Comment by irritanterik** [comment]
Also, now after reboot the old lamps reappear and removing them crashes homey.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2636
