### ISSUE TITLE
Set a Scene flow card feature request

### ISSUE THREAD

**Issue by viixxiiv** [athombv/nl.philips.hue#97]
In my bridge, I have several scenes that uses similar names.
Using the Hue apps available, the scenes are split into rooms so I can easily identify all of them.

In the set a scene flow card, I have no way of telling what rooms the scene corresponds to and worse as I have named them Warm, Cool, Nightlight for all the rooms.. 

Is there a way to show the room alongside the scene in the flow card.

**Comment by WeeJeWel** [comment]
I've looked into it but there doesn't seem to be a link made in the API that Homey can access. So unfortunately we cannot provide this feature.
