### ISSUE TITLE
Previous dim level ignored when using "set a color" card in flow

### ISSUE THREAD

**Issue by mickeman** [athombv/nl.philips.hue#99]
Is there any reason to why the lamp goes to dim level 1 if i use a "set a color" card in a flow.
If i use "set a random color" it does not, it keeps the previous level.
If i use "set the hue" card it also keeps the setting but this card is not possible to use when lamp is in temperature mode. (Nothing happens)
Very annoying when you want to change the colour but keep the previous dim level.
Or is it just me having this problem?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2634

**Comment by WeeJeWel** [comment]
This is fixed in Homey v2.0
